In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
data=pd.read_csv('churn_modelling.csv')
df=pd.DataFrame(data)
print(df)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMemb

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [3]:
df.head(2)


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   

   Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2      0.00              1          1               1   
1       1  83807.86              1          0               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0

In [4]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [5]:
X=df.iloc[:,3:-1].values
y=df.iloc[:,-1].values

In [6]:
print(X)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])


In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [10]:
X[:,1]=le.fit_transform(X[:,1])

In [11]:
print(X[:,1])

[0 2 0 ... 0 1 0]


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
ann=tf.keras.models.Sequential()

In [15]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu')) #input layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))#hidden layer1

In [17]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))#hidden layer2

In [18]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))#output layer

In [19]:
ann.compile(optimizer='adam',loss='mse',metrics=['accuracy'])

In [20]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7719 - loss: 0.1883 
Epoch 2/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7963 - loss: 0.1505  
Epoch 3/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.7997 - loss: 0.1427
Epoch 4/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.8099 - loss: 0.1392
Epoch 5/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8155 - loss: 0.1364  
Epoch 6/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.8209 - loss: 0.1343
Epoch 7/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8257 - loss: 0.1320  
Epoch 8/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.8284 - loss: 0.1303
Epoch 9/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8293 - loss: 0.1283 
Epoch 10/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.8313 - loss: 0.1266
Epoch 11/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.8343 - loss: 0.1249
Epoch 12/100
235/235 

In [21]:
print((ann.predict(sc.transform([[600,0,1,40,3,60000,2,1,1,50000]]))))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
[[0.03974036]]


In [22]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.2)
print(np.concatenate([y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)], axis=1))

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  
[[1 0]
 [1 1]
 [0 0]
 ...
 [1 0]
 [0 0]
 [0 0]]


In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm= confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1577  414]
 [ 119  390]]


0.7868

In [27]:
from sklearn.metrics import precision_score, recall_score, f1_score
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

Precision: 0.4636471990464839
Recall: 0.7642436149312377
F1 Score: 0.5771513353115727
